# Generated by Django 4.0.6 on 2022-07-12 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_meat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('customer', models.CharField(max_length=200, verbose_name='Customer')),
                ('status', models.CharField(choices=[('Solicitado', 'Solicitado'), ('Em Produção', 'Em Produção'), ('Finalizado', 'Finalizado')], default='Solicitado', max_length=11, verbose_name='Status')),
                ('bread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.bread')),
                ('meat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.meat')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'db_table': 'order',
            },
        ),
    ]
